# Generated by Django 6.0.6 on 2026-06-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('format', models.CharField(choices=[('BP', 'British Parliamentary (BP)'), ('WSDC', 'World Schools (WSDC)'), ('PS', 'Public Speaking')], default='BP', max_length=10)),
                ('num_prelim_rounds', models.PositiveIntegerField(blank=True, null=True)),
                ('current_round_seq', models.PositiveIntegerField(default=0)),
                ('speaker_score_min', models.PositiveIntegerField(default=50)),
                ('speaker_score_max', models.PositiveIntegerField(default=100)),
                ('reply_score_min', models.PositiveIntegerField(default=30)),
                ('reply_score_max', models.PositiveIntegerField(default=40)),
                ('wsdc_content_weight', models.PositiveIntegerField(default=40)),
                ('wsdc_style_weight', models.PositiveIntegerField(default=40)),
                ('wsdc_strategy_weight', models.PositiveIntegerField(default=20)),
                ('active', models.BooleanField(default=True)),
                ('public_tab_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('draw_type', models.CharField(choices=[('R', 'Random'), ('P', 'Power Paired'), ('F', 'Fold'), ('E', 'Elimination')], default='P', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_break_round', models.BooleanField(default=False)),
                ('silent', models.BooleanField(default=False)),
                ('draw_released', models.BooleanField(default=False)),
                ('results_released', models.BooleanField(default=False)),
                ('motions_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('tournament', 'seq')},
            },
        ),
    ]
