# Generated by Django 6.0.6 on 2026-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ps_content_weight',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ps_delivery_weight',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ps_language_weight',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ps_score_max',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ps_score_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ps_structure_weight',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
