# Generated by Django 6.0.6 on 2026-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_ps_content_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='public_tab_visible',
            field=models.BooleanField(default=True),
        ),
    ]
