# Generated by Django 6.0.6 on 2026-06-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_add_public_tab_visible_to_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='break_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of breaking teams for elimination rounds (e.g. 8 for Quarters, 4 for Semis)', null=True),
        ),
    ]
