# Generated by Django 6.0.6 on 2026-06-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('tournaments', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket', models.FloatField(default=0, help_text='Points bracket for power-pairing')),
                ('room_rank', models.PositiveIntegerField(default=0, help_text='1 = top room in bracket')),
                ('result_status', models.CharField(choices=[('none', 'No ballot'), ('ballot_in', 'Ballot entered'), ('confirmed', 'Confirmed')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='tournaments.round')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debates', to='venues.venue')),
            ],
            options={
                'ordering': ['-bracket', 'room_rank'],
            },
        ),
        migrations.CreateModel(
            name='DebateAdjudicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('C', 'Chair'), ('P', 'Panellist'), ('T', 'Trainee')], default='C', max_length=1)),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_adjudicators', to='participants.adjudicator')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_adjudicators', to='draw.debate')),
            ],
            options={
                'unique_together': {('debate', 'adjudicator')},
            },
        ),
        migrations.CreateModel(
            name='DebateTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('OG', 'Opening Government'), ('OO', 'Opening Opposition'), ('CG', 'Closing Government'), ('CO', 'Closing Opposition'), ('PROP', 'Proposition'), ('OPP', 'Opposition')], max_length=10)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='1=1st, 2=2nd, 3=3rd, 4=4th', null=True)),
                ('win', models.BooleanField(blank=True, null=True)),
                ('ballots_won', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_teams', to='draw.debate')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_teams', to='participants.team')),
            ],
            options={
                'unique_together': {('debate', 'position'), ('debate', 'team')},
            },
        ),
    ]
