# Generated by Django 6.0.6 on 2026-06-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
        ('participants', '0002_adj_type_and_break_size'),
        ('tournaments', '0004_adj_type_and_break_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_breaks', to='participants.adjudicator')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_breaks', to='tournaments.round')),
            ],
            options={
                'ordering': ['round', 'adjudicator__name'],
                'unique_together': {('round', 'adjudicator')},
            },
        ),
    ]
