# Generated by Django 6.0.6 on 2026-06-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draw', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudicatorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='1=poor, 5=excellent')),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ignored', models.BooleanField(default=False, help_text='Tab master can ignore outlier feedback')),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='participants.adjudicator')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='draw.debate')),
                ('source_adjudicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to='participants.adjudicator')),
                ('source_speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to='participants.speaker')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
