# Generated by Django 6.0.6 on 2026-06-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('info_slide', models.TextField(blank=True)),
                ('released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motions', to='tournaments.round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['round__seq', 'id'],
            },
        ),
    ]
