# Generated by Django 6.0.6 on 2026-06-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicator',
            name='adj_type',
            field=models.CharField(choices=[('I', 'Independent'), ('S', 'School Judge'), ('N', 'New / Trainee Judge')], default='I', max_length=1),
        ),
    ]
